#!/usr/bin/env python
from __future__ import annotations

import argparse
import json
import os
from dataclasses import asdict, fields, replace
from datetime import datetime
from pathlib import Path
from time import perf_counter

os.environ.setdefault("MPLCONFIGDIR", "/tmp/matplotlib")

import matplotlib.pyplot as plt
import numpy as np
import torch

from cse_ppo_isac.baselines import solve_sdr_solution, sinr_db
from cse_ppo_isac.config import EnvConfig
from cse_ppo_isac.env import ISACBeamformingEnv
from cse_ppo_isac.math_utils import radar_loss, zf_beamformer
from cse_ppo_isac.methods import build_ppo_config
from cse_ppo_isac.selection import is_better_candidate
from cse_ppo_isac.trainer import CSEPPOTrainer


def parse_list(value: str):
    return [item.strip().lower() for item in value.split(",") if item.strip()]


def parse_args():
    parser = argparse.ArgumentParser(description="Plot ISAC transmit beampatterns")
    parser.add_argument("--input-dir", default="", help="Log directory generated by run_experiment.py")
    parser.add_argument("--methods", default="", help="Comma list: zf,sdr,cse,structured,vanilla")
    parser.add_argument("--K", type=int, default=2)
    parser.add_argument("--sinr-db", type=float, default=12.0)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--channel-seed", type=int, default=1234)
    parser.add_argument("--updates", type=int, default=40)
    parser.add_argument("--episodes-per-update", type=int, default=64)
    parser.add_argument("--ppo-epochs", type=int, default=3)
    parser.add_argument("--hidden-dim", type=int, default=128)
    parser.add_argument("--learning-rate", type=float, default=6.0e-4)
    parser.add_argument("--constraint-reward-weight", type=float, default=1.0)
    parser.add_argument(
        "--cross-corr-weight",
        type=float,
        default=1.0,
        help="Liu-style target cross-correlation weight in Lr = Lr1 + wc Lr2.",
    )
    parser.add_argument("--eval-batch-size", type=int, default=64)
    parser.add_argument("--inference-candidates", type=int, default=16)
    parser.add_argument("--selection-rel-tol", type=float, default=0.15)
    parser.add_argument("--max-steps", type=int, default=8)
    parser.add_argument(
        "--init-mode",
        choices=("policy", "random", "zf"),
        default="policy",
        help="Initial beamformer for PPO environments when training inside this script",
    )
    parser.add_argument(
        "--pure-rl",
        action="store_true",
        help="Use random initialization and full residual actions when training inside this script",
    )
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--sdr-solver", default="SCS", choices=("SCS", "CLARABEL"))
    parser.add_argument("--sdr-max-iters", type=int, default=3000)
    parser.add_argument("--sdr-eps", type=float, default=1.0e-5)
    parser.add_argument("--scale", choices=("db", "linear"), default="db")
    parser.add_argument("--log-root", default="log")
    parser.add_argument("--output-dir", default="")
    parser.add_argument("--dpi", type=int, default=220)
    return parser.parse_args()


def make_log_dir(root: str) -> Path:
    base = Path(root) / datetime.now().strftime("%Y%m%d-%H%M%S")
    path = base
    suffix = 1
    while path.exists():
        path = Path(f"{base}_{suffix:02d}")
        suffix += 1
    path.mkdir(parents=True, exist_ok=False)
    return path


def save_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

def fresh_env(cfg: EnvConfig, seed: int, structured_action: bool = True) -> ISACBeamformingEnv:
    env = ISACBeamformingEnv(cfg, structured_action=structured_action, seed=seed)
    env.reset()
    return env


def metrics_for(env: ISACBeamformingEnv, W: np.ndarray):
    env.W = W
    metrics = env.current_metrics()
    return {
        "radar_loss": float(metrics["radar_loss"]),
        "beam_objective": float(metrics.get("beam_objective", metrics["radar_loss"])),
        "beampattern_loss": float(metrics.get("beampattern_loss", metrics["radar_loss"])),
        "cross_corr": float(metrics.get("cross_corr", 0.0)),
        "weighted_cross_corr": float(env.cfg.cross_corr_weight * metrics.get("cross_corr", 0.0)),
        "target_mean": float(metrics.get("target_mean", 0.0)),
        "target_min": float(metrics.get("target_min", 0.0)),
        "target_min_ratio": float(metrics.get("target_min_ratio", 0.0)),
        "sidelobe_ratio": float(metrics.get("sidelobe_ratio", 0.0)),
        "sidelobe_leakage": float(metrics.get("sidelobe_leakage", 0.0)),
        "target_band_errors": [
            float(value) for value in metrics.get("target_band_errors", [])
        ],
        "target_band_error_mean": float(metrics.get("target_band_error_mean", 0.0)),
        "min_sinr": float(metrics["min_sinr"]),
        "min_sinr_db": sinr_db(float(metrics["min_sinr"])),
        "feasible": bool(metrics["feasible"]),
        "cost": float(metrics["cost"]),
    }


def policy_beamformer(
    method: str,
    cfg: EnvConfig,
    args,
    output_dir: Path,
) -> tuple[np.ndarray, dict]:
    ppo_cfg = build_ppo_config(args, method)
    ppo_cfg = replace(ppo_cfg, eval_episodes=args.eval_batch_size)
    trainer = CSEPPOTrainer(cfg, ppo_cfg)
    start = perf_counter()
    history = trainer.train()
    train_time = perf_counter() - start

    best_W = None
    best = None
    rollout_cfg = replace(cfg, use_action_line_search=ppo_cfg.use_action_line_search)
    for candidate_idx in range(max(1, args.inference_candidates)):
        env = fresh_env(
            rollout_cfg, args.channel_seed, structured_action=ppo_cfg.use_nullspace_action
        )
        state = env._state()
        local_best_W = env.W.copy()
        local_best = metrics_for(env, local_best_W)
        for _ in range(cfg.max_steps):
            state_t = torch.as_tensor(state, dtype=torch.float32, device=ppo_cfg.device)
            action, _, _, _ = trainer.policy.act(
                state_t, deterministic=(candidate_idx == 0)
            )
            state, _, done, _ = env.step(action)
            current_W = env.W.copy()
            current_metrics = metrics_for(env, current_W)
            if is_better_candidate(
                current_metrics,
                local_best,
                rel_tol=ppo_cfg.selection_rel_tolerance,
            ):
                local_best_W = current_W
                local_best = current_metrics
            if done:
                break
        if best is None or is_better_candidate(
            local_best,
            best,
            rel_tol=ppo_cfg.selection_rel_tolerance,
        ):
            best_W = local_best_W
            best = local_best

    method_dir = output_dir / method
    method_dir.mkdir(parents=True, exist_ok=True)
    save_json(
        method_dir / "training_summary.json",
        {
            "method": method,
            "ppo_config": asdict(ppo_cfg),
            "train_time_sec": train_time,
            "last_history": history[-1] if history else {},
            "inference_candidates": args.inference_candidates,
        },
    )
    assert best_W is not None and best is not None
    return best_W, {"train_time_sec": train_time, **best}


def plot_patterns(
    env: ISACBeamformingEnv,
    patterns: dict[str, np.ndarray],
    metrics: dict,
    output_dir: Path,
    scale: str,
    dpi: int,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    max_power = max(float(np.max(pattern)) for pattern in patterns.values())
    desired = env.desired * max(max_power, 1.0e-9)

    plt.figure(figsize=(7.2, 4.2))
    for name, pattern in patterns.items():
        if scale == "db":
            y = 10.0 * np.log10(np.maximum(pattern, 1.0e-9))
        else:
            y = pattern
        l1 = metrics[name].get("beampattern_loss", metrics[name]["radar_loss"])
        label = f"{name} (Lr1={l1:.3g})"
        plt.plot(env.angle_grid, y, linewidth=1.8, label=label)

    if scale == "db":
        desired_y = 10.0 * np.log10(np.maximum(desired, 1.0e-9))
        ylabel = "Transmit beampattern (dB)"
    else:
        desired_y = desired
        ylabel = "Transmit beampattern"
    plt.plot(env.angle_grid, desired_y, "k--", linewidth=1.5, label="Desired")
    for theta in env.cfg.target_angles_deg:
        plt.axvline(theta, color="0.75", linestyle=":", linewidth=0.9)

    plt.xlabel("Angle (degree)")
    plt.ylabel(ylabel)
    plt.grid(True, alpha=0.3)
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.axis([-100, 100, -15, 10])
    plt.savefig(output_dir / "beampattern.png", dpi=dpi)
    plt.savefig(output_dir / "beampattern.pdf")
    plt.close()


def plot_radar_terms(
    metrics: dict,
    output_dir: Path,
    cross_corr_weight: float,
    dpi: int,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    methods = list(metrics.keys())
    if not methods:
        return

    l1 = np.asarray(
        [float(metrics[name].get("beampattern_loss", metrics[name]["radar_loss"])) for name in methods],
        dtype=np.float64,
    )
    l2 = np.asarray(
        [cross_corr_weight * float(metrics[name].get("cross_corr", 0.0)) for name in methods],
        dtype=np.float64,
    )
    lr = np.asarray(
        [float(metrics[name].get("beam_objective", metrics[name]["radar_loss"])) for name in methods],
        dtype=np.float64,
    )
    x = np.arange(len(methods), dtype=np.float64)
    width = 0.25

    plt.figure(figsize=(7.2, 4.0))
    plt.bar(x - width, l1, width=width, label="Lr1 beampattern")
    plt.bar(x, l2, width=width, label="wc*Lr2 cross-corr")
    plt.bar(x + width, lr, width=width, label="Lr")
    plt.xticks(x, methods)
    plt.ylabel("Radar loss term")
    plt.grid(True, axis="y", alpha=0.3)
    plt.legend(fontsize=8)
    plt.tight_layout()
    plt.savefig(output_dir / "radar_terms.png", dpi=dpi)
    plt.savefig(output_dir / "radar_terms.pdf")
    plt.close()


def load_env_config(input_dir: Path) -> tuple[EnvConfig, dict]:
    config_path = input_dir / "config.json"
    if not config_path.exists():
        raise FileNotFoundError(f"missing config file: {config_path}")
    config = json.loads(config_path.read_text(encoding="utf-8"))
    if "env_config" not in config:
        raise KeyError(f"{config_path} does not contain env_config")
    valid_keys = {field.name for field in fields(EnvConfig)}
    env_config = {key: value for key, value in config["env_config"].items() if key in valid_keys}
    return EnvConfig(**env_config), config


def load_saved_patterns(args) -> None:
    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir) if args.output_dir else input_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    cfg, config = load_env_config(input_dir)
    channel_seed = int(config.get("args", {}).get("channel_seed", args.channel_seed))
    env = fresh_env(cfg, channel_seed, structured_action=True)

    beamformer_path = input_dir / "beamformers.npz"
    if not beamformer_path.exists():
        raise FileNotFoundError(f"missing beamformer file: {beamformer_path}")
    beamformer_data = np.load(beamformer_path)
    saved_methods = [key for key in beamformer_data.files if key != "H"]
    methods = parse_list(args.methods) if args.methods else saved_methods

    metrics_path = input_dir / "beamformer_metrics.json"
    metrics = {}
    if metrics_path.exists():
        metrics = json.loads(metrics_path.read_text(encoding="utf-8"))

    patterns = {}
    pattern_path = input_dir / "patterns.npz"
    if pattern_path.exists():
        pattern_data = np.load(pattern_path)
        for method in methods:
            if method in pattern_data.files:
                patterns[method] = pattern_data[method]

    for method in methods:
        if method not in beamformer_data.files:
            raise KeyError(f"method {method} is not in {beamformer_path}")
        W = beamformer_data[method]
        loss, _, cross, pattern = radar_loss(
            W,
            env.grid_steering,
            env.desired,
            env.target_steering,
            cfg.cross_corr_weight,
        )
        beampattern_loss = max(0.0, float(loss) - cfg.cross_corr_weight * float(cross))
        if method not in patterns:
            patterns[method] = pattern
        metrics.setdefault(method, {})
        metrics[method]["radar_loss"] = float(loss)
        metrics[method]["beam_objective"] = float(loss)
        metrics[method]["beampattern_loss"] = float(beampattern_loss)
        metrics[method]["cross_corr"] = float(cross)
        metrics[method]["weighted_cross_corr"] = float(cfg.cross_corr_weight * cross)

    selected_patterns = {method: patterns[method] for method in methods}
    selected_metrics = {method: metrics[method] for method in methods}
    plot_patterns(env, selected_patterns, selected_metrics, output_dir, args.scale, args.dpi)
    plot_radar_terms(selected_metrics, output_dir, cfg.cross_corr_weight, args.dpi)
    save_json(output_dir / "metrics.json", selected_metrics)
    save_json(
        output_dir / "plot_config.json",
        {
            "input_dir": str(input_dir),
            "output_dir": str(output_dir),
            "methods": methods,
            "scale": args.scale,
        },
    )
    print(f"波束图已保存: {output_dir / 'beampattern.png'}", flush=True)
    print(f"雷达损失分解图已保存: {output_dir / 'radar_terms.png'}", flush=True)
    print(f"绘图指标已保存: {output_dir / 'metrics.json'}", flush=True)


def main():
    args = parse_args()
    if args.input_dir:
        load_saved_patterns(args)
        return

    methods = parse_list(args.methods) if args.methods else ["zf", "sdr", "cse"]
    output_dir = Path(args.output_dir) if args.output_dir else make_log_dir(args.log_root)
    output_dir.mkdir(parents=True, exist_ok=True)

    cfg = EnvConfig(
        num_users=args.K,
        sinr_threshold_db=args.sinr_db,
        max_steps=args.max_steps,
        init_mode="random" if args.pure_rl else args.init_mode,
        constraint_reward_weight=args.constraint_reward_weight,
        cross_corr_weight=args.cross_corr_weight,
    )
    base_env = fresh_env(cfg, args.channel_seed, structured_action=True)
    assert base_env.H is not None

    save_json(
        output_dir / "config.json",
        {
            "args": vars(args),
            "methods": methods,
            "env_config": asdict(cfg),
            "output_dir": str(output_dir),
        },
    )
    print(f"输出目录: {output_dir}", flush=True)

    beamformers: dict[str, np.ndarray] = {}
    patterns: dict[str, np.ndarray] = {}
    metrics: dict[str, dict] = {}

    for method in methods:
        print(f"计算方法: {method}", flush=True)
        env = fresh_env(cfg, args.channel_seed, structured_action=(method != "vanilla"))
        assert env.H is not None

        if method == "zf":
            W, _ = zf_beamformer(
                env.H,
                env.target_steering,
                cfg.total_power,
                cfg.noise_power,
                cfg.sinr_threshold,
                env.rng,
                loss_fn=env._loss_fn,
                comm_safety=cfg.init_comm_safety,
            )
            method_metrics = metrics_for(env, W)
        elif method == "sdr":
            method_metrics, W = solve_sdr_solution(
                cfg,
                env.H,
                env,
                solver=args.sdr_solver,
                max_iters=args.sdr_max_iters,
                eps=args.sdr_eps,
            )
            method_metrics = {**method_metrics, **metrics_for(env, W)}
        elif method in ("cse", "structured", "vanilla"):
            W, method_metrics = policy_beamformer(method, cfg, args, output_dir)
            env = fresh_env(cfg, args.channel_seed, structured_action=(method != "vanilla"))
        else:
            raise ValueError(f"unknown method: {method}")

        loss, _, cross, pattern = radar_loss(
            W,
            env.grid_steering,
            env.desired,
            env.target_steering,
            cfg.cross_corr_weight,
        )
        beampattern_loss = max(0.0, float(loss) - cfg.cross_corr_weight * float(cross))
        method_metrics["radar_loss"] = float(loss)
        method_metrics["beam_objective"] = float(loss)
        method_metrics["beampattern_loss"] = float(beampattern_loss)
        method_metrics["cross_corr"] = float(cross)
        method_metrics["weighted_cross_corr"] = float(cfg.cross_corr_weight * cross)
        beamformers[method] = W
        patterns[method] = pattern
        metrics[method] = method_metrics

    np.savez_compressed(output_dir / "beamformers.npz", **beamformers)
    np.savez_compressed(output_dir / "patterns.npz", angle_grid=base_env.angle_grid, **patterns)
    save_json(output_dir / "metrics.json", metrics)
    plot_patterns(base_env, patterns, metrics, output_dir, args.scale, args.dpi)
    plot_radar_terms(metrics, output_dir, cfg.cross_corr_weight, args.dpi)

    print(f"波束图已保存: {output_dir / 'beampattern.png'}", flush=True)
    print(f"雷达损失分解图已保存: {output_dir / 'radar_terms.png'}", flush=True)
    print(f"波束矩阵已保存: {output_dir / 'beamformers.npz'}", flush=True)
    print(f"指标已保存: {output_dir / 'metrics.json'}", flush=True)


if __name__ == "__main__":
    main()
